wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705783332.556659
    t:
      1:
      - 1
      - 55
      3:
      - 13
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 5
      - 9
      13: darwin-arm64
