wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705834850.251685
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 4
      - 5
      - 9
      13: darwin-arm64
